steps:
- name: 'ubuntu'
  args: ['bash', '-c', 'apt-get update && apt-get install -y wget gnupg && apt-get install -y make && apt-get install -y curl && apt-get install -y software-properties-common && apt-get install -y lsb-release  && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && apt-get update && apt-cache policy docker-ce && apt-get install -y docker-ce &&  make compile']
  dir: 'cacheUpdater'
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/lax-gateway/cacheupdater:$REVISION_ID", "."]
  dir: 'cacheUpdater/tmp'
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/lax-gateway/cacheupdater:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/cacheupdater'
  - 'cacheupdater=gcr.io/lax-gateway/cacheupdater:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=forecast'
