apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reporting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: reporting
    spec:
      containers:
      - name: reporting
        image: gcr.io/lax-gateway/reporting:1.0
        imagePullPolicy: Always
